### PR TITLE
feat: tailing process

### PR DESCRIPTION
**Pull request by ThePrimeagen**

### CODE REVIEW

**Comment by cgsdev0** [comment]
alternatively, you could keep this script unix-y and do this:
```
watch -n 0.5 vmrss $PID
```

**Comment by ThePrimeagen** [comment]
@cgsdev0 I don't know what you're saying, but I really appreciate the words on the screen,

Also feel free to make a PR and I can look at what you're trying to say.

**Comment by cgsdev0** [comment]
> @cgsdev0 I don't know what you're saying, but I really appreciate the words on the screen,

@ThePrimeagen i was just saying you can use [watch](https://linux.die.net/man/1/watch) instead of building this functionality into your script

unix philosophy; something something "do one thing well"

**Comment by ThePrimeagen** [comment]
Here I am, not even knowing watch

Reading books
Taking Notes

Teach me @cgsdev0

**Pull request merged**
